spring:
  profiles: dev,production
  cloud:
    stream:
      function:
        definition: generate;process;sink
        bindings:
          generate-out-0: source1
          process-in-0: source1
          process-out-0: processed
          sink-in-0: processed

        bindingServiceProperties:
          defaultBinder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
